[package]
name = "noah/tens-of-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
Component = "sleitnick/component@2.4.6"
Trove = "sleitnick/trove@1.0.0"
Loader = "sleitnick/loader@2.0.0"
Signal = "sleitnick/signal@1.5.0"
Spring = "brittonfischer/spring@0.1.0"
FastCastRedux = "encodedvenom/fastcastredux@0.1.3"
PartCache = "4igz/partcache@1.0.1"
Roact = "roblox/roact@1.4.4"
Rodux = "roblox/rodux@3.0.0"
RoactRodux = "roblox/roact-rodux@0.3.0"
EnumList = "sleitnick/enum-list@2.1.0"
Timer = "sleitnick/timer@1.1.2"
RoactSpring = "chriscerie/roact-spring@2.0.0"

React = "jsdotlua/react@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"

ClientCast = "indominiso/clientcast@1.0.7"
Comm = "sleitnick/comm@1.0.1"

Shake = "sleitnick/shake@0.1.7"