[package]
name = "noah/tens-of-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
Component = "sleitnick/component@2.4.6"
Trove = "sleitnick/trove@1.0.0"
spring = "brittonfischer/spring@0.1.0"
