[package]
name = "noah/tens-of-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
Component = "sleitnick/component@2.4.6"
Trove = "sleitnick/trove@1.0.0"
Loader = "sleitnick/loader@2.0.0"
Signal = "sleitnick/signal@1.5.0"
Spring = "brittonfischer/spring@0.1.0"
FastCastRedux = "encodedvenom/fastcastredux@0.1.3"
PartCache = "4igz/partcache@1.0.1"
Roact = "roblox/roact@1.4.4"
Rodux = "roblox/rodux@3.0.0"